# Generated by Django 5.2.17 on 2026-09-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=50)),
                ('age', models.FloatField(blank=True, help_text='Age in years (optional)', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('selected_symptoms', models.JSONField(default=list, help_text='List of symptoms reported by the user.')),
                ('other_symptoms', models.TextField(blank=True, help_text='Additional observations entered by the user.', null=True)),
                ('predicted_disease', models.CharField(help_text='Most likely preliminary condition identified by the screening engine.', max_length=200)),
                ('confidence', models.FloatField(help_text='Confidence percentage (0-100%).')),
                ('risk_level', models.CharField(help_text='Screening risk classification (LOW, MEDIUM, HIGH, CRITICAL).', max_length=20)),
                ('matched_symptoms', models.JSONField(blank=True, default=list, help_text='Symptoms from user selection that matched the predicted disease.')),
                ('recommendation', models.TextField(help_text='Guidance provided to the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diagnosis Record',
                'verbose_name_plural': 'Diagnosis Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('animal_types', models.JSONField(default=list, help_text='List of animal types prone to this disease (lowercase).')),
                ('symptoms', models.JSONField(default=dict, help_text='Mapping of symptom names (lowercase) to importance weights (e.g. 1-3).')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('recommended_action', models.TextField(help_text='Immediate farmer guidance and veterinary consultation instructions.')),
            ],
            options={
                'verbose_name': 'Disease Knowledge Record',
                'verbose_name_plural': 'Disease Knowledge Base',
                'ordering': ['name'],
            },
        ),
    ]
